# Generated by Django 4.2.11 on 2025-03-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_admin', '0005_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='balance',
        ),
        migrations.AddField(
            model_name='balance',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
