# Generated by Django 4.2.11 on 2025-03-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_admin', '0006_remove_account_balance_amount_remove_balance_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='logout',
            name='customer',
        ),
        migrations.AddField(
            model_name='login',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logout',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logout',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
