# Generated by Django 4.2.11 on 2025-03-31 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_admin', '0007_remove_login_customer_remove_logout_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Custom_admin.customer'),
        ),
        migrations.AddField(
            model_name='logout',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Custom_admin.customer'),
        ),
    ]
